version: '3.5'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres

  editora:
    image: gabazar/editora-api:1.0.0
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "8090:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql:5432/dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

volumes:
  postgres-data: