version: '3.5'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080
    depends_on:
      - postgres
    networks:
      - backend

  editora:
    image: gabazar/editora-api:1.0.0
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/dev
      - SHOW_SQL=false
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge